### ISSUE TITLE
BayesComm removed from CRAN

### ISSUE THREAD

**Issue by davharris** [goldingn/BayesComm#14]
>Archived on 2015-07-01 as maintainer address <nick.golding@zoo.ox.ac.uk> bounced.

https://cran.r-project.org/web/packages/BayesComm/index.html

I know you aren't planning to update the package, but it seems like this could be a pretty easy fix. Would you be able to resubmit the current CRAN version with your new email address?

**Comment by goldingn** [comment]
Christ, that was quick.

Yup, will do battle with the new CRAN tests over the next couple of days and get this sorted. Thanks for letting me know!

**Comment by goldingn** [comment]
I've changed all of the top-level bits now with 71d23aaa56580, but this version is incompatible with latest Rcpp interface, so I'll need to fix that before it passes CRAN checks.

I could have reverted to the version previously on CRAN, updated email address and title case and specified a particular Rcpp version. I've no idea whether that would be CRAN-acceptable though and in any case would be difficult to install. I would rather get the predict function etc. up there too, so this is a better route.

Should find time to re-configure the cpp bits soon

**Comment by goldingn** [comment]
Huh, seems now to run the examples just fine in `R CMD check --as-cran` on my mac (commit c6ad709a719). Maybe it was just the NAMESPACE stuff that was borked.

I just need to adhere to the new rules on registering S3 methods, try on a couple of OS's and we should be good to go.

@davharris are you running a windows machine? If so would you mind checking on there when I've fixed the latest lot? I can handle mac and linux (though checks on more machines always welcome).

**Comment by goldingn** [comment]
Now we're cooking. As of commit d2dcd70775d this now passes checks in R 3.2.1 on my mac and linux box. Will try building using winbuilder next and submit ASAP.

For the sake of completeness, this is the command I used:

```
R CMD build ~/Dropbox/Github/BayesComm && R CMD check --as-cran BayesComm_0.1-2.tar.gz
```

these are sessionInfos on the two machines:
```
R version 3.2.1 (2015-06-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
```

```
 version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin14.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
```

and on both machines there's only one NOTE raised:

```
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Nick Golding
<nick.golding.research@gmail.com>’
New submission

Package was archived on CRAN

CRAN repository db overrides:
  X-CRAN-Comment: Archived on 2015-07-01 as maintainer address
    <nick.golding@zoo.ox.ac.uk> bounced.
```

**Comment by goldingn** [comment]
After an initial rejection - I only tested with the stable version of R but the version in development requires explicit importation of base functions (as in commit 524a7c1) - the package is now in CRAN:

https://cran.r-project.org/web/packages/BayesComm/index.html
