### ISSUE TITLE
Apparent bugs in rwish

### ISSUE THREAD

**Issue by davharris** [goldingn/BayesComm#16]
On my machine, I can run the code pasted below and have the following results:

1) usually, `r_BayesComm` will be a vector with 492 `-1`s and 508 `1`s. In this case `r_stats` will be a vector starting with 0.2607197 -0.0487728 -0.3571361  0.1185012 -0.2122375  0.1099040

2) Occasionally, `r_BayesComm` will be a vector of values close to zero (e.g. 1.01925860639709e-113).  In this case, `r_stats` will be a different vector, starting with 0.48158048  0.37782313 -0.48798432  0.40718493 -0.33612164  0.03201664

3) More frequently, `r_BayesComm` will be a vector of `NaN`, and r_stats will be a vector starting with -0.51311400  0.03831854  0.18563242 -0.64805035 -0.08207458 -0.15182066

Regardless of which case we're in on a particular run, I don't think we're getting good samples from the Wishart distribution (at least for element 1,2 of the matrix; the other elements seem like they might be less problematic?).  I also think it means that `rwish` isn't deterministic given the random number seed. Maybe something important is being declared but not initialized? I don't know enough C++ to tell.

Could we swap in `stats::rWishart` instead of `BayesComm::rwish`?

```
set.seed(1)

Sigma = diag(5)
df = 10


r_BayesComm = replicate(
  1000,
  cov2cor(BayesComm:::rwish(Sigma, df))[1,2]
)

table(r_BayesComm)

r_stats = replicate(
  1000,
  cov2cor(stats::rWishart(1, df, Sigma)[,,1])[1,2]
)

head(r_stats)
```

**Comment by davharris** [comment]
Oh, I see.  `BayesComm::rwish` expects a `df` to be a vector whose length is the number of species.  The non-deterministic and incorrect behavior was probably from C++ reading past the end of `df` and finding garbage.

Probably worth adding an assertion that keeps that kind of undefined behavior from happening, but I no longer think that it's affecting `BCfit`'s behavior.

**Comment by davharris** [comment]
But now I don't understand why the df value for species `i` should depend on which column it belongs to?

I guess I really don't understand any of the code in `sample_R.R` or in `rwish.cpp`, which is making it hard for me to figure out what's going on with the prior.  Is there a document that describes the algorithm? 

Thanks for bearing with me

**Comment by goldingn** [comment]
Hiya,

Sorry I'm mostly avoiding emails etc. mid-relocation, so this is a brief one.

There are some more details in the SI for this paper: http://www.parasitesandvectors.com/content/8/1/367

I'm pretty rusty on the details of the implementation, but think you're right that the distribution has a scalar df parameter. If the function takes a vector, I imagine it's just the scalar repeated the length of the vector.

Obviously that's awful design-wise and is probably the result of some overzealous optimization of the C++ bits (it runs faster if you don't have to allocate a vector on each iteration).

If that's the case, there should be something at the top of the BCfit function definition which sets and replicates the df.

Sorry I can't be more help, I'm only on my phone at the moment!

**Comment by goldingn** [comment]
Looks like the df vector is defined in sample_R:

v <- priR[1]
df <- v:(v - ncol(S) + 1)

Which appears to do part of rwish's job for it. It seems more likely that I was too lazy to code that bit into C++ :)

**Comment by davharris** [comment]
Sorry, I still don't understand.  Why do we want a vector with different values of `df` for each species? I didn't see anything about that in the supplemental information you linked.

**Comment by goldingn** [comment]
Sorry, that was confusing. There's only one, scalar df specified, no matter the size of the covariance matrix. That's v in the above snippet.

But the algorithm for sampling from the distribution converts this into a descending series of integers. That's the second line in the snippet above, assigned to df.
E.g. with 6 degrees of freedom on a 3-species model, you'd use the vector [6 5 4].

This vector is created in sample_R, not in rwish because sloppy design.

Does that make sense?

**Comment by davharris** [comment]
Partially fixed in https://github.com/goldingn/BayesComm/pull/17
