### ISSUE TITLE
Notify users of changes to `predict`

### ISSUE THREAD

**Issue by davharris** [goldingn/BayesComm#23]
It's returning a matrix now instead of an array, so any existing code that uses it will break. Should we notify users with a message on package startup?

**Comment by goldingn** [comment]
Remind me why it returns a matrix instead of an array...?
I thought (thought I haven't looked too deeply yet) that it returned a marginal (i.e. environment-only) prediction of the 2D community prediction matrix for each of the posterior samples, all stored in a 3D array?

**Comment by davharris** [comment]
Oh, you’re probably right.  I hadn’t thought about it in a few weeks.  But the interpretation definitely changes from conditioning on Z to marginalizing over it.

**Comment by goldingn** [comment]
Right, it's the 'if there were no other species present' prediction, but still includes all of the posterior draws.

The alternative would be to summarize the predictive posterior for the user, but I think most people would want to do that themselves.

Ah MCMC, so useful but so messy.

**Comment by davharris** [comment]
Not sure what our options would be for summarizing it.  We could look at the coda package and see what they use, I suppose.

I think that you may have mis-typed or I’m mis-interpreting regarding "if there were no other species present”; if the other species were all absent, that would provide a lot of information about the value of Z.

**Comment by goldingn** [comment]
Yup, you're right, that's not what it is at all. I'm not sure what the equivalent to marginal is in ecological terms then...

I think the same array shape would be good for now. There are already summary methods (wrapping coda) for the parameter chains, perhaps giving the predictions a class and summary method would be a good compromise?

**Comment by davharris** [comment]
Marginal is, “ignoring the other species, what’s the probability that we’ll see this species”.

Arrays it is then.  I’ll create an issue (#25)

**Comment by davharris** [comment]
Oh, and what do you think about notifying users? Startup message?

**Comment by goldingn** [comment]
So long as 'ignoring' is interpreted correctly :) But yeah, I think that's pretty much it.

A startup message sounds good. Boldface note in the appropriate doc would be good too.

So this is just tot say that the type of prediction has changed, rather than the shape of the result?

**Comment by davharris** [comment]
Right. Once we update the predict function to produce an array, I think it makes sense to let them know that the meaning of the numbers in the array has changed. 

Dave

**Comment by davharris** [comment]
Obviated by #30
